tasks api
KosarevaMarina1985/fixme-ts-tasks pull request #2
Opened 2022-01-22 21:07 UTC by KosarevaMarina1985

2022-01-23 18:30 UTC, AntiHero requested changes

2022-01-23 18:30 UTC, AntiHero commented on src/api/task.ts
> +    this._id = null;
почему null? почему сразу не задавать уникальный идентификатор?

2022-01-23 18:30 UTC, AntiHero commented on src/api/taskLocalStorage.test.ts
> +    localStorage.clear();
а мы можем вынести наверх повторяющийся код, чтобы в каждом describe не писать одно и то же?
https://jestjs.io/docs/setup-teardown

2022-01-23 18:30 UTC, AntiHero commented on src/api/taskLocalStorage.ts
> +  async get(): Promise<Task[]> {
методы для работы с хранилищем должны быть асинхронными, это не асинхронный метод

2022-01-23 18:30 UTC, AntiHero commented on src/api/taskLocalStorage.ts
> +  async save(tasks: Task[]): Promise<void> {
это тоже не асинхронный метод

2022-01-23 18:30 UTC, AntiHero commented on src/api/taskLocalStorage.ts
> +export class TaskLocalStorage implements Storage<Task> {
согласно заданию интерфейс должен поддерживать crud, тут он реализован частично насколько я вижу

2022-01-23 18:30 UTC, AntiHero commented on src/api/taskService.test.ts
> +    taskLocalStorageMock = mocked({
можешь пожалуйста объяснить для чего ты используешь здесь и далее mocked? jest.mocked используются для пердоставления типов для мок модуля, на основе его исходного кода. какой конкретно модуль ты здесь мокаешь?

2022-01-23 18:30 UTC, AntiHero commented on src/api/taskService.ts
> +    return this.storage.saveNew(task);
где реализация метода saveNew?

2022-01-23 18:30 UTC, AntiHero commented on src/api/taskService.test.ts
> +      save: jest.fn(),
для чего мокать методы, чью работу мы хотим реально проверить? убедиться, что в базу данных что-то записывается

2022-01-23 18:41 UTC, KosarevaMarina1985 commented on src/api/task.ts
> +    this._id = null;
исходя из моего опыта разработки бэкенда. когда там пишем crud, то при создании сущности идентификатор присваивается после сохранения в базе данных(самой бд), как правило, это какое-то инкрементное bigDecimal  поле, поэтому при создании новой сущности она идет без ид, а после сохранения в бд возвращется с идентификатором.

2022-01-23 18:45 UTC, KosarevaMarina1985 commented on src/api/taskLocalStorage.ts
> +export class TaskLocalStorage implements Storage<Task> {
это класс сохранения, который используется в классе, в котором реализуются круд методы. Вернее, это конкретная реализация интерфейса Storage, которая использует localStorage. Какая-то другая имплементация использует другое хранилище. Соответственно этот класс отвечает за чисто сохранение в каком-то хранилище. А класс, реализующий круд метоlы - TaskService

2022-01-23 18:46 UTC, KosarevaMarina1985 commented on src/api/taskService.ts
> +    return this.storage.saveNew(task);
в классе TaskLocalStorage

2022-01-23 18:47 UTC, AntiHero commented on src/api/task.ts
> +    this._id = null;
так и есть, твой аргумент в этом плане более весомый, но применительно к нашему дз, наши БД, с которыми мы работаем (LS/JSON) не умеют генерировать id, может только FB (и это необязательно)

2022-01-23 18:48 UTC, KosarevaMarina1985 commented on src/api/taskService.test.ts
> +      save: jest.fn(),
мы не хотим здесь проверить эти методы. Эти методы проверяются в тестах для соответствующего класса TaskLocalStorage в файле taskLocalStorage.test.ts. А здесь проверяются методы класса TaskService

2022-01-23 18:51 UTC, KosarevaMarina1985 commented on src/api/task.ts
> +    this._id = null;
я, если честно, вообще пропустила пункт про базы LS/JSON, пока не знаю что это, надо читать

2022-01-23 18:53 UTC, AntiHero commented on src/api/task.ts
> +    this._id = null;
LS - это LocalStorage, JSON - json db

2022-01-23 18:55 UTC, AntiHero commented on src/api/taskService.test.ts
> +      save: jest.fn(),
Хорошо, если ты не хочешь проверять эти методы замокай тогда модуль taskLocalStorage, для чего создавать какие-то объекты, с похожим интерфейсом

2022-01-23 19:04 UTC, KosarevaMarina1985 commented on src/api/taskService.test.ts
> +      save: jest.fn(),
Так я его и мокаю. Есть сервис с круд методами TaskService, который в  конструктор принимает имплементацию Storage, в моем случае TaskLocalStorage, которая основана на localStorage. соответственно, так как методы TaskLocalStorage протестированы в другом месте, здесь я их мокаю. let taskLocalStorageMock: Storage<Task>;   taskLocalStorageMock = mocked(....).

2022-01-23 19:14 UTC, AntiHero commented on src/api/taskService.test.ts
> +      save: jest.fn(),
подожди, ты не его мокаешь, ты мокаешь некий объект, со схожим интерфейсом, который сама же потом и приводишь к нужному тебе типу Storage

2022-01-23 19:23 UTC, KosarevaMarina1985 commented on src/api/taskService.test.ts
> +      save: jest.fn(),
как это  со схожим интерфейсом? есть конкретный интерфейс interface Storage<T>. Мой мок на имплементацию этого интерфейса let taskLocalStorageMock: Storage<Task>; Например, взять тест it("removes correctly", ... Я мокаю два необходимых мне метода, и проверяю, что они реально вызываются   при вызове   await taskService.remove(task2);

    expect(taskLocalStorageMock.get).toHaveBeenCalled();
    expect(taskLocalStorageMock.save).toHaveBeenCalledWith([task1]);

2022-01-23 19:44 UTC, AntiHero commented on src/api/taskService.test.ts
> +      save: jest.fn(),
да, ты создаёшь мок модуля, со схожим опять же интерфейсом,но ты не мокаешь модуль taskLocalStorage, ты его вообще не импортируешь даже в свой тест, так можно делать, но для чего, если у тебя есть конкретный модуль taskLocalStorage, который возвращает тебе конкретный класс taskLocalStorage, экземпляр которого ты можешь передавать в TaskService, для чего тебе создавать объект ака модуль, с похожим интерфейсом, если у тебя уже есть готовый модуль. И да, опять же, так можно сделать, как делаешь это ты, потому что твой TaskService принимает любое хранилище с заданным интерфейсом, но при чём тут тогда taskLocalStorageMock, если это не мок модуля taskLocalStorage

2022-01-24 21:18 UTC, KosarevaMarina1985 commented on src/api/status.ts
> +export enum Status {
исправила

2022-01-24 21:18 UTC, KosarevaMarina1985 commented on src/api/task.ts
> +    this._id = null;
задаю в конструкторе

2022-01-24 21:18 UTC, KosarevaMarina1985 commented on src/api/taskLocalStorage.test.ts
> +    localStorage.clear();
вынесла

2022-01-24 21:20 UTC, KosarevaMarina1985 commented on src/api/taskLocalStorage.ts
> +  async get(): Promise<Task[]> {
вот здесь я тогда не знаю как его сделать асинхронным. я думала, что он асинхронный

2022-01-24 21:20 UTC, KosarevaMarina1985 commented on src/api/taskService.test.ts
> +    taskLocalStorageMock = mocked({
сделала по-другому

2022-01-25 16:06 UTC, merged